// export const COUNTER_CHANGE = 'COUNTER_CHANGE'

export const INCREASE_COUNTER = 'INCREASE_COUNTER'
export const DECREASE_COUNTER = 'DECREASE_COUNTER'
export const CLEAR_DATA = 'CLEAR_DATA'

export const FETCHING_DATA = 'FETCHING_DATA'